/** Basic Calculator Service A simple calculator API that performs basic arithmetic operations.
  *
  * OpenAPI spec version: 1.0.0 Contact: contact@kindservices.co.uk
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  */

// this model was generated using model.mustache
package demo.calc.model
import scala.math.BigDecimal
import scala.util.control.NonFatal

// see https://com-lihaoyi.github.io/upickle/
import upickle.default.{ReadWriter => RW, macroRW}
import upickle.default.*

case class Calculate200Response(
    /* Result of the arithmetic operation. */

    result: BigDecimal = 0
) {

  def asJson = write(this)

}

object Calculate200Response {

  given RW[Calculate200Response] = macroRW

  def fromJsonString(jason: String): Calculate200Response = try {
    read[Calculate200Response](jason)
  } catch {
    case NonFatal(e) => sys.error(s"Error parsing json '$jason': $e")
  }

  def manyFromJsonString(jason: String): List[Calculate200Response] = try {
    read[List[Calculate200Response]](jason)
  } catch {
    case NonFatal(e) => sys.error(s"Error parsing json '$jason' as list: $e")
  }

  def mapFromJsonString(jason: String): Map[String, Calculate200Response] = try {
    read[Map[String, Calculate200Response]](jason)
  } catch {
    case NonFatal(e) => sys.error(s"Error parsing json '$jason' as map: $e")
  }

}
