/** Basic Calculator Service A simple calculator API that performs basic arithmetic operations.
  *
  * OpenAPI spec version: 1.0.0 Contact: contact@kindservices.co.uk
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  */

// this model was generated using model.mustache
package demo.calc.model
import scala.util.control.NonFatal

// see https://com-lihaoyi.github.io/upickle/
import upickle.default.{ReadWriter => RW, macroRW}
import upickle.default.*

case class Calculate400Response(
    /* Error message describing the invalid input. */

    message: String = ""
) {

  def asJson = write(this)

}

object Calculate400Response {

  given RW[Calculate400Response] = macroRW

  def fromJsonString(jason: String): Calculate400Response = try {
    read[Calculate400Response](jason)
  } catch {
    case NonFatal(e) => sys.error(s"Error parsing json '$jason': $e")
  }

  def manyFromJsonString(jason: String): List[Calculate400Response] = try {
    read[List[Calculate400Response]](jason)
  } catch {
    case NonFatal(e) => sys.error(s"Error parsing json '$jason' as list: $e")
  }

  def mapFromJsonString(jason: String): Map[String, Calculate400Response] = try {
    read[Map[String, Calculate400Response]](jason)
  } catch {
    case NonFatal(e) => sys.error(s"Error parsing json '$jason' as map: $e")
  }

}
