/** Basic Calculator Service A simple calculator API that performs basic arithmetic operations.
  *
  * OpenAPI spec version: 1.0.0 Contact: contact@kindservices.co.uk
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  */

package demo.calc.model

// model package
import upickle.default._
import java.time.*
import java.time.format.DateTimeFormatter

given ReadWriter[ZonedDateTime] = readwriter[String].bimap[ZonedDateTime](
  zonedDateTime => DateTimeFormatter.ISO_INSTANT.format(zonedDateTime),
  str => ZonedDateTime.parse(str, DateTimeFormatter.ISO_INSTANT)
)

given ReadWriter[LocalDateTime] = readwriter[String].bimap[LocalDateTime](
  zonedDateTime => DateTimeFormatter.ISO_INSTANT.format(zonedDateTime),
  str => LocalDateTime.parse(str, DateTimeFormatter.ISO_INSTANT)
)

given ReadWriter[LocalDate] = readwriter[String].bimap[LocalDate](
  zonedDateTime => DateTimeFormatter.ISO_INSTANT.format(zonedDateTime),
  str => LocalDate.parse(str, DateTimeFormatter.ISO_INSTANT)
)

given ReadWriter[OffsetDateTime] = readwriter[String].bimap[OffsetDateTime](
  zonedDateTime => DateTimeFormatter.ISO_INSTANT.format(zonedDateTime),
  str =>
    println(s"parsing >${str}<")
    OffsetDateTime.parse(str, DateTimeFormatter.ISO_INSTANT)
)

given ReadWriter[BigDecimal] = readwriter[Long].bimap[BigDecimal](
  dbl => dbl.toLong,
  str =>
    println(s"parsing dbl >${str}<")
    BigDecimal(str)
)
