//> using scala "3.3.1"
//> using lib "com.lihaoyi::cask:0.9.2"
//> using lib "com.lihaoyi::scalatags:0.8.2"
/** Basic Calculator Service A simple calculator API that performs basic arithmetic operations.
  *
  * OpenAPI spec version: 1.0.0 Contact: contact@kindservices.co.uk
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  */

// this file was generated from app.mustache
package demo.calc

import _root_.demo.calc.model.*
import _root_.demo.calc.api.*

/** This trait encapsulates the business logic (services) and the http routes which handle the http
  * requests sent to those services.
  *
  * There are default 'not implemented' implementations for the service.
  *
  * If you wanted fine-grained control over the routes and services, you could extend the
  * cask.MainRoutes and mix in this trait by using this:
  *
  * \{\{\{ override def allRoutes = appRoutes \}\}\}
  *
  * More typically, however, you would extend the 'BaseApp' class
  */
trait AppRoutes {
  def appDefaultService: DefaultService = DefaultService()
  def routeForDefault: DefaultRoutes    = DefaultRoutes(appDefaultService)

  def appRoutes = Seq(
    routeForDefault
  )
}
