//> using scala "3.3.1"
//> using lib "com.lihaoyi::cask:0.9.2"
//> using lib "com.lihaoyi::scalatags:0.8.2"
/** Basic Calculator Service A simple calculator API that performs basic arithmetic operations.
  *
  * OpenAPI spec version: 1.0.0 Contact: contact@kindservices.co.uk
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  */

// this file was generated from app.mustache
package demo.calc

import _root_.demo.calc.model.*
import _root_.demo.calc.api.*

/** This class was created with the intention of being extended by some runnable object, passing in
  * the custom business logic services
  */
class BaseApp(
    override val appDefaultService: DefaultService = DefaultService(),
    override val port: Int = sys.env.get("PORT").map(_.toInt).getOrElse(8080)
) extends cask.MainRoutes
    with AppRoutes {

  /** routes for the UI Subclasses can override to turn this off
    */
  def openApiRoute: Option[cask.Routes] = Option(OpenApiRoutes(port))

  override def allRoutes = appRoutes ++ openApiRoute

  override def host: String = "0.0.0.0"

  def start() = locally {
    initialize()
    println(box(s""" 🚀 browse to localhost:$port 🚀
        |      host : $host
        |      port : $port
        |   verbose : $verbose
        | debugMode : $debugMode
        |""".stripMargin))

    // if java.awt.Desktop.isDesktopSupported then {
    //    java.awt.Desktop.getDesktop.browse(new java.net.URI(s"http://localhost:${port}"))
    // }
  }
}
