//> using scala "3.3.1"
//> using lib "com.lihaoyi::cask:0.9.2"
//> using lib "com.lihaoyi::scalatags:0.8.2"
/** Basic Calculator Service A simple calculator API that performs basic arithmetic operations.
  *
  * OpenAPI spec version: 1.0.0 Contact: contact@kindservices.co.uk
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  */

// this file was generated from app.mustache
package demo.calc

import _root_.demo.calc.model.*
import _root_.demo.calc.api.*

/** This is an example of how you might extends BaseApp for a runnable application.
  *
  * See the README.md for how to create your own app
  */
object ExampleApp extends BaseApp() {
  start()
}
