/** Basic Calculator Service A simple calculator API that performs basic arithmetic operations.
  *
  * OpenAPI spec version: 1.0.0 Contact: contact@kindservices.co.uk
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  */

package demo.calc

def box(str: String): String = {
  val lines  = str.linesIterator.toList
  val maxLen = (0 +: lines.map(_.length)).max
  val boxed = lines.map { line =>
    s" | ${line.padTo(maxLen, ' ')} |"
  }
  val bar = " +-" + ("-" * maxLen) + "-+"
  (bar +: boxed :+ bar).mkString("\n")
}
