//> using scala "3.3.1"
//> using lib "com.lihaoyi::cask:0.8.3"
//> using lib "com.lihaoyi::scalatags:0.12.0"
/** Basic Calculator Service A simple calculator API that performs basic arithmetic operations.
  *
  * OpenAPI spec version: 1.0.0 Contact: contact@kindservices.co.uk
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  */

// generated from apiService.mustache
package demo.calc.api

import _root_.demo.calc.model.Calculate200Response
import _root_.demo.calc.model.Calculate400Response
import _root_.demo.calc.model.CalculateRequest

object DefaultService {
  def apply(): DefaultService = new DefaultService {
    override def calculate(
        calculateRequest: CalculateRequest
    ): ServiceResponse[Calculate200Response] = ServiceResponse.notImplemented
  }
}

/** The Default business-logic
  */
trait DefaultService {

  /** Perform arithmetic operation
    *
    * @return
    *   Calculate200Response
    */

  def calculate(calculateRequest: CalculateRequest): ServiceResponse[Calculate200Response]
}
