name: OpenAPI Generator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run OpenAPI Generator
      run: |
        docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli validate \
            -i v1/service.yaml
